I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 315, in script
    nas "ВЫ ЧЁ БЛЯТЬ ДЕЛАЕТЕ?! ВЫ ЧЁ СОВСЕМ ОХУЕЛИ?! ВЫ ЕЁ НАХУЙ ЧУТЬ НЕ УБИЛИ!" with vpunh
  File "game/script.rpy", line 315, in <module>
    nas "ВЫ ЧЁ БЛЯТЬ ДЕЛАЕТЕ?! ВЫ ЧЁ СОВСЕМ ОХУЕЛИ?! ВЫ ЕЁ НАХУЙ ЧУТЬ НЕ УБИЛИ!" with vpunh
NameError: name 'vpunh' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 315, in script
    nas "ВЫ ЧЁ БЛЯТЬ ДЕЛАЕТЕ?! ВЫ ЧЁ СОВСЕМ ОХУЕЛИ?! ВЫ ЕЁ НАХУЙ ЧУТЬ НЕ УБИЛИ!" with vpunh
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\ast.py", line 929, in execute
    say_menu_with(self.with_, renpy.game.interface.set_transition)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\ast.py", line 748, in say_menu_with
    what = renpy.python.py_eval(expression)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 315, in <module>
    nas "ВЫ ЧЁ БЛЯТЬ ДЕЛАЕТЕ?! ВЫ ЧЁ СОВСЕМ ОХУЕЛИ?! ВЫ ЕЁ НАХУЙ ЧУТЬ НЕ УБИЛИ!" with vpunh
NameError: name 'vpunh' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.3.23091805
Сохры 1.0
Thu Jan 16 02:02:45 2025
