I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "game/screens.rpy", line 147, in <module>
    xsize len(what)
NameError: name 'what' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\main.py", line 670, in main
    run(restart)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\main.py", line 74, in run
    renpy.translation.init_translation()
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\translation\__init__.py", line 593, in init_translation
    renpy.store._init_language() # type: ignore
  File "renpy/common/00start.rpy", line 83, in _init_language
    renpy.change_language(language)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\translation\__init__.py", line 685, in change_language
    new_change_language(tl, language)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\translation\__init__.py", line 639, in new_change_language
    i.apply()
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\ast.py", line 2974, in apply
    value = renpy.python.py_eval(expr)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\all_Kvasych_games\cren'pie\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/screens.rpy", line 147, in <module>
    xsize len(what)
NameError: name 'what' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.1.3.23091805
Сохры 1.0
Fri Jan 10 22:29:31 2025
